name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      - run: docker-compose -p xmtp -f "tool/local-node/docker-compose.yml" up -d
      - run: flutter pub get
      - run: dart format . --set-exit-if-changed
      - run: flutter test --dart-define=TEST_SERVER_ENABLED=true
        # See tool/test-lib/README.md for more details.
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/tool/test-lib/linux-x64"
      - run: docker-compose -p xmtp -f "tool/local-node/docker-compose.yml" down
        if: always()